### ISSUE TITLE
Error using SimpleCABACMex

### ISSUE THREAD

**Issue by ngcthuong** [christianrohlfing/ISScabac#2]
Hello, 

Thank you for release the CABAC source code. 
I ran the "cabacDemo" on window 10 and come with this error. 
Any suggestion to fix this?

Thank you 

> Error using SimpleCABACMex
> Error: bitstreamfile access error
> 
> 
> Error in cabacWrapper/encodeStart (line 43)
> 			SimpleCABACMex('encodeStart', obj.cabac_handle);
> 
> Error in cabacDemo (line 84)
>   encoder.encodeStart();

**Comment by aachenmax** [comment]
Hi AtenaKid,

we fixed a bug relating to the file handling of the CABAC wrapper class. Hopefully, this also fixed the issue you are mentioning.

BR,
Max

**Comment by ngcthuong** [comment]
Thank you. It runs perfect now.
